### ISSUE TITLE
Problem in lateral of AR tags

### ISSUE THREAD

**Issue by patrickelectric** [robotadasufsc/Larc2017Simulator#12]
![selection_066](https://cloud.githubusercontent.com/assets/1215497/26533355/35d97ce0-43ee-11e7-9cb0-d7da5ca5223a.png)
![selection_065](https://cloud.githubusercontent.com/assets/1215497/26533356/37e0e5fa-43ee-11e7-867a-d8d25687ac3e.png)

**Comment by patrickelectric** [comment]
@Williangalvani if possible, please add a white board around the tags like in the real thing

**Comment by Williangalvani** [comment]
source?

**Comment by patrickelectric** [comment]
![image](https://cloud.githubusercontent.com/assets/1215497/26533444/86e4e3e4-43ef-11e7-8cc2-70b1b0c626a4.png)

**Comment by patrickelectric** [comment]
![image](https://cloud.githubusercontent.com/assets/1215497/26533537/a20a20f2-43f0-11e7-966f-8224bc5d57e6.png)
